// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ready_next/core/storage/hive_helper.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppLanguageAdapter());
    registerAdapter(AppThemePaletteAdapter());
    registerAdapter(AppThemeSeedColorAdapter());
    registerAdapter(DashboardPreferencesAdapter());
    registerAdapter(DashboardShortcutPreferenceAdapter());
    registerAdapter(DashboardStartupModuleAdapter());
    registerAdapter(DashboardWidgetPreferenceAdapter());
    registerAdapter(LocalSettingsModelAdapter());
    registerAdapter(ThemeModeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppLanguageAdapter());
    registerAdapter(AppThemePaletteAdapter());
    registerAdapter(AppThemeSeedColorAdapter());
    registerAdapter(DashboardPreferencesAdapter());
    registerAdapter(DashboardShortcutPreferenceAdapter());
    registerAdapter(DashboardStartupModuleAdapter());
    registerAdapter(DashboardWidgetPreferenceAdapter());
    registerAdapter(LocalSettingsModelAdapter());
    registerAdapter(ThemeModeAdapter());
  }
}
