import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ready_next/shared/presentation/icons/app_icons.dart';

void main() {
  test('all product icon catalogs use Material Symbols', () {
    const icons = <IconData>[
      AppIcons.dashboard,
      AppIcons.inventory,
      AppIcons.health,
      AppIcons.workspaces,
      AppIcons.orders,
      AppIcons.settings,
      AppIcons.tasks,
      AppIcons.file,
      AppIcons.folder,
      AppIcons.folders,
      AppIcons.wiki,
      AppIcons.activity,
      AppIcons.notifications,
      AppIcons.chat,
      AppIcons.help,
      AppIcons.search,
      AppIcons.menu,
      AppIcons.add,
      AppIcons.chevronRight,
      AppIcons.privateSpace,
      AppIcons.members,
      AppIcons.workflow,
      AppIcons.pin,
      AppIcons.kanban,
      AppIcons.whiteboard,
      AppIcons.automations,
      AppIcons.corkboard,
      AppIcons.upload,
      AppIcons.download,
      AppIcons.close,
      AppIcons.delete,
      AppIcons.star,
      AppIcons.clock,
      AppIcons.users,
      AppIcons.sort,
      AppIcons.grid,
      AppIcons.list,
      AppIcons.refresh,
      AppIcons.checkCircle,
      AppIcons.slash,
      AppIcons.lock,
      AppIcons.alertCircle,
      AppIcons.image,
      AppIcons.document,
      AppIcons.video,
      AppIcons.volume,
      AppIcons.documentText,
      AppIcons.table,
      AppIcons.presentation,
      AppIcons.archive,
      AppIcons.code,
      AppIcons.moreVertical,
      AppIcons.chevronDown,
      AppIcons.chevronUp,
      AppIcons.share,
      AppIcons.link,
      AppIcons.user,
      WorkspaceIcons.dashboard,
      WorkspaceIcons.workspaces,
      WorkspaceIcons.settings,
      WorkspaceIcons.tasks,
      WorkspaceIcons.file,
      WorkspaceIcons.folder,
      WorkspaceIcons.folders,
      WorkspaceIcons.wiki,
      WorkspaceIcons.activity,
      WorkspaceIcons.notifications,
      WorkspaceIcons.chat,
      WorkspaceIcons.menu,
      WorkspaceIcons.add,
      WorkspaceIcons.chevronRight,
      WorkspaceIcons.privateSpace,
      WorkspaceIcons.members,
      WorkspaceIcons.workflow,
      WorkspaceIcons.pin,
      WorkspaceIcons.kanban,
      WorkspaceIcons.whiteboard,
      WorkspaceIcons.automations,
      WorkspaceIcons.corkboard,
      WorkspaceIcons.upload,
      WorkspaceIcons.download,
      WorkspaceIcons.close,
      WorkspaceIcons.delete,
      WorkspaceIcons.star,
      WorkspaceIcons.clock,
      WorkspaceIcons.users,
      WorkspaceIcons.sort,
      WorkspaceIcons.grid,
      WorkspaceIcons.list,
      WorkspaceIcons.refresh,
      WorkspaceIcons.checkCircle,
      WorkspaceIcons.slash,
      WorkspaceIcons.lock,
      WorkspaceIcons.alertCircle,
      WorkspaceIcons.image,
      WorkspaceIcons.document,
      WorkspaceIcons.video,
      WorkspaceIcons.volume,
      WorkspaceIcons.documentText,
      WorkspaceIcons.table,
      WorkspaceIcons.presentation,
      WorkspaceIcons.archive,
      WorkspaceIcons.code,
      WorkspaceIcons.moreVertical,
      WorkspaceIcons.chevronDown,
      WorkspaceIcons.chevronUp,
      WorkspaceIcons.share,
      WorkspaceIcons.link,
      WorkspaceIcons.user,
    ];

    expect(icons, isNotEmpty);
    for (final icon in icons) {
      expect(icon.fontPackage, 'material_symbols_icons');
      expect(icon.fontFamily, 'MaterialSymbolsRounded');
    }
  });
}
